export const hpCauses = [
  {
    id: "challenge",
    label: "روز · چالش (۵ دمیج)",
    delta: -5,
    amount: "5",
    mode: "damage" as const,
  },
  {
    id: "chaos-vote",
    label: "روز · آشوب‌گر (۱۰ دمیج به‌ازای هر رأی)",
    delta: -10,
    amount: "10",
    mode: "damage" as const,
  },
  {
    id: "vote-duel",
    label: "روز · رأی دو / رأی‌گیری (۲۰ دمیج)",
    delta: -20,
    amount: "20",
    mode: "damage" as const,
  },
  {
    id: "boss-shot",
    label: "شب · شات رئیس مافیا (۱۰۰ دمیج)",
    delta: -100,
    amount: "100",
    mode: "damage" as const,
  },
  {
    id: "archer-shot",
    label: "شب · شات کمان‌دار (۷۵ دمیج)",
    delta: -75,
    amount: "75",
    mode: "damage" as const,
  },
  {
    id: "poison",
    label: "شب · سم‌ساز (مقدار دلخواه)",
    amount: "",
    mode: "damage" as const,
  },
  {
    id: "healer",
    label: "شب · هیلر / طبیب (افزایش HP)",
    amount: "",
    mode: "heal" as const,
  },
  {
    id: "sage-heal",
    label: "شب · حکیم (۵+ HP)",
    delta: 5,
    amount: "5",
    mode: "heal" as const,
  },
  {
    id: "wizard-box",
    label: "روز · جعبه جادوگر (۵۰ دمیج)",
    delta: -50,
    amount: "50",
    mode: "damage" as const,
  },
  {
    id: "roulette",
    label: "رولت روسی · همسان‌سازی HP دو بازیکن",
    amount: "",
    mode: "damage" as const,
  },
  {
    id: "manual",
    label: "سایر / تغییر دستی",
    amount: "",
    mode: "damage" as const,
  },
];
